# Generated by Django 3.1.4 on 2020-12-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=255)),
                ('first_name', models.CharField(help_text='Enter your first name or first initial.', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Enter your street address.', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Enter your city.', max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField(blank=True)),
                ('website', models.URLField(blank=True, help_text='Enter your website or link for letting clients get in touch', max_length=255)),
                ('profession', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
