# Generated by Django 3.1.4 on 2020-12-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name or first initial.', max_length=255)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=255)),
                ('middle_name', models.CharField(blank=True, help_text='Enter your middle name or intial.', max_length=255)),
                ('dba', models.CharField(blank=True, help_text='Doing Business As', max_length=255)),
                ('website_url', models.URLField(blank=True, help_text='Enter your website or link for letting clients get in touch', max_length=255)),
                ('email', models.EmailField(help_text='Enter your first name or first initial.', max_length=64, null=True)),
                ('display_email_on_profile', models.BooleanField(default=False, help_text='Check if you would like your email displayed on your directory page')),
                ('street', models.CharField(blank=True, help_text='Enter your street address.', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Enter your city.', max_length=255)),
                ('summary', models.CharField(blank=True, help_text='One or two lines for that will be displayed in the main directory (maximum of 180 characters). Upgrading to an Enhanced entry will let you also add a much larger description.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Please write a fuller description about your, your firm and the services you offer.', null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
