# Generated by Django 3.1.4 on 2020-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
