# Generated by Django 3.1.4 on 2020-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20201222_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zipcode',
            field=models.CharField(default='95476', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
