# Generated by Django 3.1.4 on 2020-12-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.state'),
        ),
    ]
