# Generated by Django 3.1.4 on 2020-12-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20201223_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
